services:
  telegrambot:
    container_name: telegrambot

    build: .

    restart: unless-stopped

    env_file:
      - .env

    volumes:
    - /vol1/Docker/TelegramBot/logs:/app/logs
    - /vol1/Docker/TelegramBot/data:/app/data

    working_dir: /app

    healthcheck:
      test: ["CMD", "python", "-c", "print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
