services:
  telegrambot:
    container_name: telegrambot

    build: .

    restart: unless-stopped

    environment:
      ALLOWED_USER_ID: "1834853831"
      BOT_TOKEN: "YOUR_BOT_TOKEN"
      STATUS_FILE: "/app/data/status.env"
      LOG_FILE: "/app/logs/bot.log"

    volumes:
      - /vol1/Docker/TelegramBot/data:/app/data
      - /vol1/Docker/TelegramBot/logs:/app/logs

    working_dir: /app

    healthcheck:
      test: ["CMD", "python", "-c", "print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
